### ISSUE TITLE
guidance.llms.OpenAI.cache.clear() no longer works

### ISSUE THREAD

**Issue by rabidgremlin** [microsoft/guidance#171]
**The bug**
Calls to guidance.llms.OpenAI.cache.clear() (as documented in README) no longer work in v0.0.58

Causes error:

```
File "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", line 127, in build
 guidance.llms.OpenAI.cache.clear() # clear any cached responses as we start new session
AttributeError: 'DiskCache' object has no attribute 'clear'
```

**System info (please complete the following information):**
 - Ubuntu, Mac
 - Guidance Version (`guidance.__version__`): 0.0.58

**Comment by slundberg** [comment]
Thank you! That was an error with the cache revamp, just patched (and added a test for it).

**Comment by scworland** [comment]
Where in the process should I clear the cache? Using the agent example from the readme returns the exact same output every time it is run regardless of the presence of the `guidance.llms.Transformers.cache.clear()` command. This occurs whether running the code in a notebook or as a script, and persists even in a fresh terminal session. 

```python
import guidance

guidance.llm = guidance.llms.OpenAI("gpt-4")
guidance.llms.Transformers.cache.clear()

role_simulator = guidance('''
{{#system~}}
You are a helpful assistant
{{~/system}}
                                           
{{#user~}}
You will answer the user as {{role}} in the following conversation. At every step, I will provide you with the user input, as well as a comment reminding you of your instructions. Never talk about the fact that you are an AI, even if the user asks you. Always answer as {{role}}.
{{#if first_question}}You can also start the conversation.{{/if}}
{{~/user}}
                                           
{{~! The assistant either starts the conversation or not, depending on if this is the first or second agent }}
{{#assistant~}}
Ok, I will follow these instructions.
{{#if first_question}}Let me start the conversation now:
{{role}}: {{first_question}}{{/if}}
{{~/assistant}}

{{~! Then the conversation unrolls }}
{{~#geneach 'conversation' stop=False}}
{{#user~}}
User: {{set 'this.input' (await 'input')}}
Comment: Remember, answer as a {{role}}. Start your utterance with {{role}}:
{{~/user}}

{{#assistant~}}
{{gen 'this.response' temperature=0 max_tokens=300}}
{{~/assistant}}
{{~/geneach}}''')

republican = role_simulator(role='Republican', await_missing=True)
democrat = role_simulator(role='Democrat', await_missing=True)

first_question = '''What do you think is the best way to stop inflation?'''
republican = republican(input=first_question, first_question=None)
democrat = democrat(input=republican["conversation"][-2]["response"].strip('Republican: '), first_question=first_question)
for i in range(2):
    republican = republican(input=democrat["conversation"][-2]["response"].replace('Democrat: ', ''))
    democrat = democrat(input=republican["conversation"][-2]["response"].replace('Republican: ', ''))
print('Democrat: ' + first_question)
for x in democrat['conversation'][:-1]:
    print('Republican:', x['input'])
    print()
    print(x['response'])
```
